#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

typeset -U path
path=($HOME/bin $HOME/.cabal/bin $HOME/.local/bin $HOME/.npm-packages/bin $path)
export path

export EDITOR="emacsclient -t"
export MAKEFLAGS="-j2"
export MANWIDTH=72
export TEXMFHOME=$HOME/.texmf
#export XDG_CONFIG_HOME=$HOME/.config
