
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) \
          && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Editors
#

export EDITOR='emacs'
export VISUAL='nano'
export PAGER='less'

#
# Man
#

manpath=(
    $HOME/.npm-global/share/man
    /usr/local/opt/grep/share/man
    /usr/local/opt/man-db/lib/share/man
    /usr/local/opt/findutils/share/man
    /usr/local/opt/coreutils/libexec/gnuman
    /usr/local/opt/gnu-tar/share/man
    /usr/local/opt/bash/share/man
    /usr/local/opt/make/libexec/share/man
    /usr/share/man
)

export MANWIDTH=72
export MANOPT="--no-justification"
export manpath

#
# Path
#

path=(
    $HOME/bin
    $HOME/.local/bin
    $HOME/.cargo/bin
    $HOME/.npm-global/bin
    /Library/TeX/texbin/
    /usr/local/opt/grep/libexec/gnubin
    /usr/local/opt/man-db/libexec/bin
    /usr/local/opt/findutils/libexec/gnubin
    /usr/local/opt/coreutils/libexec/gnubin
    /usr/local/opt/gnu-tar/libexec/gnubin
    /usr/local/opt/bash/bin
    /usr/local/opt/make/libexec/gnubin
    /usr/local/sbin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
)

export path
typeset -gU cdpath fpath mailpath manpath path

#
# Java
#

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Cj
#

if [[ -e $HOME/.cj/environment ]]; then source $HOME/.cj/environment; fi

#
# Aws
#

if [[ -e $HOME/.aws/environment ]]; then source $HOME/.aws/environment; fi
