#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

eval "$(direnv hook zsh)"

alias idea='open -na "IntelliJ IDEA.app" --args'

alias ls='ls --color=auto --human-readable --group-directories-first'
alias grep='grep --color=auto'

function chpwd() {
    emulate -L zsh
    ls
}

zstyle ':completion:*' rehash true

# The following lines were added by compinstall
zstyle :compinstall filename '/Users/abrice/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source $HOME/.zprezto/modules/syntax-highlighting/external/zsh-syntax-highlighting.zsh

for k in "${(@k)ZSH_HIGHLIGHT_STYLES}"; do
    ZSH_HIGHLIGHT_STYLES[$k]=${ZSH_HIGHLIGHT_STYLES[$k]:gs/fg=red,bold/fg=yellow,bold}
    ZSH_HIGHLIGHT_STYLES[$k]=${ZSH_HIGHLIGHT_STYLES[$k]:gs/fg=green,bold/fg=red}
    ZSH_HIGHLIGHT_STYLES[$k]=${ZSH_HIGHLIGHT_STYLES[$k]:gs/fg=green/fg=red,bold}
done

# unsetopt sharehistory

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

fpath=(~/.zsh $fpath)

precmd() { precmd() { print "" } }

# fnm
export PATH="/Users/antbrice1/Library/Application Support/fnm:$PATH"
eval "`fnm env --use-on-cd`"
